---
driver:
  name: ec2
  region: us-east-1
  instance_type: t2.micro
  tags: {Name: "chef-test-kitchen-worker"}

  # Note: security_group_ids, aws_ssh_key_id, and ssh_key should be defined in
  # `$HOME/.kitchen/config.yml`. These values vary for each AWS account.
  # Ensure that 'security_group_ids' is set to allow remote SSH access.
  # security_group_ids: ["sg-5973d520", "sg-5f7ed826"]
  # aws_ssh_key_id: cms-karl

# transport:
  # ssh_key: ~/workspaces/cms/aws-cms-karl.pem

provisioner:
  name: chef_solo

platforms:
  - name: rhel-7.2
    driver:
      image_id: ami-2051294a
    transport:
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[hhsdevcloud_environment::default]
    attributes:
  - name: ldap_server_and_client
    run_list:
      - recipe[hhsdevcloud_environment::ldap_server]
      - recipe[hhsdevcloud_environment::ldap_client]
    attributes:

